services:
  # Backend API Service
  - type: web
    name: nabeel-restaurant-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RESTREVIEWS_DB_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/sample_restaurants?retryWrites=true&w=majority
      - key: RESTREVIEWS_NS
        value: sample_restaurants
      - key: ALLOWED_ORIGINS
        value: https://nabeel-restaurant.vercel.app
