FROM node:20-slim

COPY . .

RUN npm install

ENV RESTREVIEWS_DB_URI=mongodb://admin:password@192.168.1.101:27017
ENV RESTREVIEWS_NS=sample_restaurants
ENV PORT=5000

EXPOSE 5000

CMD [ "npm" , "run" , "start"]